baseURL: https://beansbreadbooks.jonahweissman.com
disablePathToLower: true
languageCode: en-us
title: Beans, Bread, Books
theme: PaperMod

menu:
  main:
    - identifier: posts
      name: posts
      url: /post/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40
    - identifier: guestbook
      name: guestbook
      url: /guestbook/
params:
    poemTypes:
        - writing
        - original
    homeInfoParams:
        Title: Jonah's Amtrak adventures
        Content: updates from life on the rails
    mainSections:
      - post
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: false
    assets:
        disableHLJS: true
    dateFormat: "January 2, 2006 3:04 PM MST"
markup:
  # goldmark:
  #   renderer:
  #     hardWraps: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 2
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
