baseURL: https://travel.tannerdw.com
disablePathToLower: true
languageCode: en-us
title: tanner dw goes
theme: PaperMod

menu:
  main:
    # - identifier: posts
    #   name: posts
    #   url: /post/
    #   weight: 10
    # - identifier: writing
    #   name: writing
    #   url: /writing/
    #   weight: 10
    - identifier: post archive
      name: post archive
      url: /post-archive/
      weight: 20
    - identifier: writing archive
      name: writing archive
      url: /writing-archive/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40
params:
    poemTypes:
        - writing
        - original
    homeInfoParams:
        Title: meanderings
        Content: sometimes i explore
    mainSections:
      - post
      - writing
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: false
    assets:
        disableHLJS: true
    # socialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"
markup:
  # goldmark:
  #   renderer:
  #     hardWraps: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 2
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
